function fearIndex = calculateFearIndex(features)
    % Calculate the Fear Index using the given formula
    fearIndex = features.F1 + 2 * features.F2 + features.F3 + ...
                0.5 * features.F4 + features.F5 + 2 * features.F6 + ...
                features.F7 + 5 * features.F8 + 0.001 * features.F9 + ...
                0.5 * features.F10;
end
